### PR TITLE
Add Rails 5.1 support

### LINKED ISSUE #65: Rails 5.1: Relax version spec in gemspec
Rails 5.1 is now out. DefaultValueFor requires Rails < 5.1.

```
default_value_for (~> 3.0) was resolved to 3.0.0, which depends on
      activerecord (< 5.0, >= 3.2.0)
```
Relax the gem version requirements?

### PR DESCRIPTION
**Pull request by chrisarcand**
Adds support for Rails 5.1, unlocking the gemspec for the new release. No incompatibilities. Also cleans up Rakefile tasks (they were broken) and removes deprecation warning in tests.

Closes #65

### CODE REVIEW

**Comment by drubin** [comment]
@FooBarWidget / @norman any change of merging this and releasing a new gem?

**Comment by chrisarcand** [comment]
@FooBarWidget @norman Bump?

**Comment by ckritzinger** [comment]
Bump again :)

**Comment by norman** [comment]
Thanks for taking this on - I've merged this to master and we'll get a new gem up on Rubygems soon.

**Pull request merged**
