### PR TITLE
Fix stored attributes + allows_nil => false

### LINKED ISSUE #59: default_value_for on a non-column attribute doesn't honor initialized attributes when `allows_nil` is false.
Here's what's currently in [default_value_for.rb](https://github.com/FooBarWidget/default_value_for/blob/master/lib/default_value_for.rb#L160)

``` ruby
        attribute_blank = if column && column.type == :boolean
          attributes[attribute].nil?
        else
          attributes[attribute].blank?
        end
```

Since the attributes hash is the only thing inspected, for non-column values this will always be nil.

It seems like the fix for this should be as easy as switching from checking the attributes hash to using the getter method.

### PR DESCRIPTION
**Pull request by njakobsen**
Fix bug that prevented default value from working when a value was passed in at initialization, and `:allows_nil => false`. Only the attributes hash was being read, so stored attributes were not being detected.

Closes #59.

### CODE REVIEW

**Comment by feldpost** [comment]
@norman Do you think this could be merged?

**Comment by rywall** [comment]
@norman Anything I can do to help this PR get merged?

**Comment by chrisarcand** [comment]
@njakobsen @feldpost @rywall [Released as 3.0.4](https://github.com/FooBarWidget/default_value_for/releases/tag/release-3.0.4)

**Comment by rywall** [comment]
@chrisarcand Thank you!!

**Pull request merged**
