### PR TITLE
Add Rails 5.0 support

### PR DESCRIPTION
**Pull request by matthewd**
The changes are all in `clear_attribute_changes`:

* it's now public on ActiveRecord (though not ActiveModel) -- this might be accidental (@sgrif?), but checking `respond_to?` is more correct anyway
* it requires its argument to be an array
* it raises `ActiveModel::MissingAttributeError` if called with a non-attribute

### CODE REVIEW

**Comment by connorshea** [comment]
Any updates on this?

**Comment by jrafanie** [comment]
@norman What can we do help get this merged and released?   Thank you!

**Comment by connorshea** [comment]
Rails 5.0.0.rc1 is out today: https://github.com/rails/rails/releases/tag/v5.0.0.rc1

There shouldn't be any breaking changes between rc1 and the stable release, so it should be safe to release :)

**Comment by norman** [comment]
Sorry for the slow response, I'll have a look at this soon.



-- 
Sent from my phone

**Comment by connorshea** [comment]
You're fine, happy to see this isn't abandoned :D

**Comment by colorfulberry** [comment]
Can you merge this ?

**Comment by connorshea** [comment]
@norman Bumping since [Rails 5 was released today](http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/), thanks for your work on this gem!

**Comment by connorshea** [comment]
cc: @FooBarWidget

**Comment by tuvistavie** [comment]
Hoping this will be merged soon, in the meanwhile the Appraisals file could be updated to use 5.0 instead of the beta.

**Comment by 0x01f7** [comment]
@norman Can you push the latest version to rubygems.org? Thanks!

**Comment by FooBarWidget** [comment]
Gem has been pushed now. Thanks for all the work and please don't forget to tag this release.

**Comment by norman** [comment]
> please don't forget to tag this release

Done!

**Comment by connorshea** [comment]
<3 thanks @FooBarWidget @norman!

**Pull request merged**
