### PR TITLE
Support Rails 5.2

### PR DESCRIPTION
**Pull request by AlexKovynev**
It seems like with 5.2.0.rc2 all already fine.

### CODE REVIEW

**Comment by chrisarcand** [comment]
As 5.2 is not released yet, I'll wait to merge this until RailsConf when 5.2 is expected to be released. Thanks for looking at this, good to be ready for it so soon!

**Comment by AlexKovynev** [comment]
5.2 already here!:)

**Comment by chrisarcand** [comment]
Indeed it is!

**Comment by chrisarcand** [comment]
Released as 3.1.0. Thank you! 💕

**Pull request merged**
