### PR TITLE
Support Rails 6.x

### PR DESCRIPTION
**Pull request by igor-drozdov**
We can loose the dependency versions in order to be able to update to Rails 6.x

### CODE REVIEW

**Comment by igor-drozdov** [comment]
@chrisarcand do these changes make sense to you, could you please have a look?

**Comment by chrisarcand** [comment]
Hello! Could you add the latest versions to CI (see [here](https://github.com/FooBarWidget/default_value_for/blob/master/Appraisals))? We should run the tests against these latest versions before suggesting that the gem actually works with those versions (I do not use or maintain this gem anymore, so I can't say whether it does or not - but a green build is good enough for me!)

**Comment by igor-drozdov** [comment]
@chrisarcand Thanks for your answer! Done 🏓

**Review by chrisarcand — APPROVED** [review]
✅

```
10:09:06 ~/code/FooBarWidget/default_value_for(554563e) » be rake test:railsall
/Users/chris/.rbenv/versions/2.6.6/bin/ruby test.rb
/Users/chris/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

Testing with Active Record version 3.2.22.5

Testing with Action Pack version 3.2.22.5

Run options: --seed 27770

# Running:

...................................

Finished in 0.346196s, 101.0988 runs/s, 153.0925 assertions/s.

35 runs, 53 assertions, 0 failures, 0 errors, 0 skips
/Users/chris/.rbenv/versions/2.6.6/bin/ruby test.rb
/Users/chris/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.0.13/lib/active_support/core_ext/object/duplicable.rb:82: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

Testing with Active Record version 4.0.13

Testing with Action Pack version 4.0.13

Run options: --seed 33035

# Running tests:

.....................................

Finished tests in 0.332406s, 111.3097 tests/s, 159.4436 assertions/s.

37 tests, 53 assertions, 0 failures, 0 errors, 0 skips
/Users/chris/.rbenv/versions/2.6.6/bin/ruby test.rb
/Users/chris/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.1.16/lib/active_support/core_ext/object/duplicable.rb:82: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

Testing with Active Record version 4.1.16

Testing with Action Pack version 4.1.16

Run options: --seed 41333

# Running:

.....................................

Finished in 0.277829s, 133.1754 runs/s, 190.7648 assertions/s.

37 runs, 53 assertions, 0 failures, 0 errors, 0 skips
/Users/chris/.rbenv/versions/2.6.6/bin/ruby test.rb
/Users/chris/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

Testing with Active Record version 4.2.11.1

Testing with Action Pack version 4.2.11.1

Run options: --seed 7164

# Running:

.....................................

Finished in 0.294806s, 125.5063 runs/s, 179.7792 assertions/s.

37 runs, 53 assertions, 0 failures, 0 errors, 0 skips
/Users/chris/.rbenv/versions/2.6.6/bin/ruby test.rb

Testing with Active Record version 5.0.7.2

Testing with Action Pack version 5.0.7.2

Run options: --seed 61679

# Running:

.....................................

Finished in 0.358226s, 103.2868 runs/s, 147.9513 assertions/s.
37 runs, 53 assertions, 0 failures, 0 errors, 0 skips
/Users/chris/.rbenv/versions/2.6.6/bin/ruby test.rb

Testing with Active Record version 5.1.7

Testing with Action Pack version 5.1.7

Run options: --seed 56427

# Running:

.....................................

Finished in 0.450406s, 82.1481 runs/s, 117.6716 assertions/s.
37 runs, 53 assertions, 0 failures, 0 errors, 0 skips
/Users/chris/.rbenv/versions/2.6.6/bin/ruby test.rb

Testing with Active Record version 5.2.3

Testing with Action Pack version 5.2.3

Run options: --seed 50878

# Running:

.....................................

Finished in 0.463149s, 79.8879 runs/s, 114.4340 assertions/s.
37 runs, 53 assertions, 0 failures, 0 errors, 0 skips
/Users/chris/.rbenv/versions/2.6.6/bin/ruby test.rb

Testing with Active Record version 6.0.0

Testing with Action Pack version 6.0.0

Run options: --seed 25364

# Running:

.....................................

Finished in 0.400483s, 92.3884 runs/s, 132.3402 assertions/s.
37 runs, 53 assertions, 0 failures, 0 errors, 0 skips
/Users/chris/.rbenv/versions/2.6.6/bin/ruby test.rb

Testing with Active Record version 6.1.1

Testing with Action Pack version 6.1.1

Run options: --seed 23717

# Running:

.....................................

Finished in 0.381366s, 97.0197 runs/s, 138.9741 assertions/s.
37 runs, 53 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by chrisarcand** [comment]
https://rubygems.org/gems/default_value_for/versions/3.4.0

**Comment by igor-drozdov** [comment]
@chrisarcand Thanks for the approval and for releasing the new version!

**Pull request merged**
