### PR TITLE
Support rails 8.0

### PR DESCRIPTION
**Pull request by k-tsuchiya-jp**
### Motivation / Background

Support rails 8.0

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by k-tsuchiya-jp** [comment]
``` bash
$ ruby test.rb

Testing with ruby version 3.3.6

Testing with Active Record version 8.0.0

Testing with Action Pack version 8.0.0

Run options: --seed 55055

# Running:

......................................

Finished in 0.217141s, 175.0015 runs/s, 257.8969 assertions/s.

38 runs, 56 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by jrafanie** [comment]
Thanks @k-tsuchiya-jp.  I've pushed a commit to get rails 8.0 into the CI test matrix.

**Comment by jrafanie** [comment]
Released in 4.1.0.  Please report any bugs or problems!  Thanks for the contribution.

**Comment by k-tsuchiya-jp** [comment]
@jrafanie
Thank you for review, merge, and also for adding the changes to `ci.yaml`.
I really appreciate you going as far as handling the release – it was a great help!

**Pull request merged**
